<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="shortcut icon" href="/web/images/favicon/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/web/images/favicon/favicon-32x32.png" type="image/png">
    <link rel="icon" type="image/x-icon" href="/web/images/favicon/favicon.ico">
    <link rel="icon" type="image/png" sizes="32x32" href="/web/images/favicon/favicon-32x32.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rock+3D&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Overpass&family=Rock+3D&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                fontFamily: {
                    'rock3d': ['"Rock 3D"'],
                    'overpass': ['Overpass', 'sans-serif'], //task text
                    'icons': ['"Material Icons"'], //icons
                }
            }
        }
    </script>
</head>

<body class="bg-[url('../web/images/engin-akyurt-IZj7vckPGiw-unsplash.jpg')] bg-cover bg-center max-w-screen">
    <div class="flex flex-col justify-center items-center h-screen">
        <h1 class="text-5xl font-rock3d">TO-DO</h1>
        <h2 class="mb-4">by Albert&Joan v0.5</h2>
        <?php
        //Mostra possibles missatges d'error relacionats amb el login
        if (isset($_SESSION["errors"])) { ?>
            <div class="border rounded-md border-red-700 font-bold text-red-700 text-center mx-auto max-w-xs p-2 m-2 opacity-80 bg-white/80 rounded-md shadow shadow-lg">
                <?php
                foreach ($_SESSION["errors"] as $missatge) {
                    echo $missatge . PHP_EOL;
                }
                unset($_SESSION["errors"]);
                ?>
            </div>
        <?php
        }
        ?>
        <?php
        //Mostra possibles missatges relacionats amb el login
        if (isset($_SESSION["messages"])) { ?>
            <div class="border rounded-md border-green-700 font-bold text-green-700 text-center mx-auto max-w-xs p-2 m-2 opacity-80 bg-white/80 rounded-md shadow shadow-lg">
                <?php
                foreach ($_SESSION["messages"] as $missatge) {
                    echo $missatge . PHP_EOL;
                }
                unset($_SESSION["messages"]);
                ?>
            </div>
        <?php
        }
        ?>
        <h1 class="w-11/12 max-w-xs lg:w-11/12 bg-yellow-500/60 text-2xl text-center font-bold rounded-t-md p-1 font-overpass align-middle"><span class="font-icons mr-2 align-middle">login</span>Login</h1>
        <form action=<?= WEB_ROOT . "/welcome"; ?> method="post" class="w-11/12 max-w-xs lg:w-11/12 bg-white/40 shadow shadow-lg rounded-b-md px-8 pt-6 pb-8 mb-4">
            <input type="text" name="username" placeholder="Username" required class="shadow appearance-none border rounded w-full py-2 px-3 text-yellow-700 leading-tight focus:outline-none focus:shadow-outline"><br>
            <input type="password" name="password" placeholder="Password" required class="my-8 shadow appearance-none border rounded w-full py-2 px-3 text-yellow-700 leading-tight focus:outline-none focus:shadow-outline"><br>
            <input type="submit" name="process-login" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full">
        </form>

    </div>

</body>

</html>