<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-yellow-600">
    <div class="flex flex-col justify-center items-center h-screen">
        <h1 class="text-3xl">TO-DO</h1>
        <h2 class="mb-4">by Albert&Joan v0.5</h2>
        <?php
        //Mostra possibles missatges d'error relacionats amb el login
        if (isset($_SESSION["errors"])) { ?>
            <div class="border bg-white rounded-md border-red-700 font-bold text-red-700 text-center mx-auto max-w-xs p-2 m-2">
                <?php
                foreach ($_SESSION["errors"] as $missatge) {
                    echo $missatge . PHP_EOL;
                }
                unset($_SESSION["errors"]);
                ?>
            </div>
        <?php
        }
        ?>
        <?php
        //Mostra possibles missatges relacionats amb el login
        if (isset($_SESSION["messages"])) { ?>
            <div class="border bg-white rounded-md border-green-700 font-bold text-green-700 text-center mx-auto max-w-xs p-2 m-2">
                <?php
                foreach ($_SESSION["messages"] as $missatge) {
                    echo $missatge . PHP_EOL;
                }
                unset($_SESSION["messages"]);
                ?>
            </div>
        <?php
        }
        ?>        
        <h1 class="w-full max-w-xs bg-yellow-500 text-3xl text-center font-bold rounded-t-md p-2">Login</h1>
        <form action=<?= WEB_ROOT . "/welcome"; ?> method="post" class="w-full max-w-xs bg-white shadow-md rounded-b-md px-8 pt-6 pb-8 mb-4">
            <input type="text" name="username" placeholder="Username" required class="shadow appearance-none border rounded w-full py-2 px-3 text-yellow-700 leading-tight focus:outline-none focus:shadow-outline"><br>
            <input type="password" name="password" placeholder="Password" required class="my-8 shadow appearance-none border rounded w-full py-2 px-3 text-yellow-700 leading-tight focus:outline-none focus:shadow-outline"><br>
            <input type="submit" name="process-login" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full">
        </form>

    </div>

</body>

</html>