<?php
//Start general app controller
$controller = new ApplicationController();
//Check login status
if (isset($_POST["process-login"])) { //Attempting login
    //Recover data sent by post
    $usuari_contrasenya = new Request();
    $valors_post = $usuari_contrasenya->getAllParams();
    //Read the data sent by the form on /login/index and clean it up
    $userData[0] = htmlspecialchars($valors_post['username']);
    $userData[1] = htmlspecialchars($valors_post['password']);
    if ($controller->processLogin($userData)) {
        //Correct user logged in. Save it into the session for use in the app as an array with user id, username and name.
        $_SESSION["loggedUser"]['session'] = $_COOKIE['PHPSESSID'];
        $_SESSION["loggedUser"]['id'] = $controller->getUser()->getId();
        $_SESSION["loggedUser"]['username'] = $controller->getUser()->getUser();
        $_SESSION["loggedUser"]['name'] = $controller->getUser()->getName();
        echo "<h1>Login amb èxit. Benvingut/da " . $_SESSION["loggedUser"]['name'] . "</h1>" . PHP_EOL;
    } else {
        //Redirect to login with error. Erase all post variables and logout any users for safety
        unset($_POST);
        $controller->processLogout();
        session_start();
        $_SESSION["errors"] = array("Dades de login incorrectes per accedir a aquesta pàgina, identifica't.");
        header('Location: ' . WEB_ROOT . '/login');
    }
} else if (isset($_SESSION["loggedUser"]) && $_SESSION["loggedUser"]['session'] != $_COOKIE['PHPSESSID']) { //The logged user session is different than the current session
    $controller->processLogout();
} else if (isset($_SESSION["loggedUser"]) && $_SESSION["loggedUser"]['session'] == $_COOKIE['PHPSESSID']) { //User is already logged in. Should be unset upon "log out" button push.
    //Proceed to execute the rest of this file.
}
?>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
</head>

<body>

    <?php

    echo '<p class="text-red-500 font-bold">This is the WELCOME.phtml view body.</p>' . PHP_EOL;


    ?>

</body>

</html>